version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_health_bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=postgresql://botuser:botpass@db:5432/healthbot
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: healthbot_postgres
    restart: always
    environment:
      POSTGRES_USER: botuser
      POSTGRES_PASSWORD: botpass
      POSTGRES_DB: healthbot
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: